# BerryGrid Environment


tasks: ["red", "green", "blue", "purple", "yellow", "grey"]
num_cumulants: 6
num_demonstrators: 1
phaseII: False
lr: 0.002
total_steps: 10000000
total_steps_phaseI: 10000000
total_steps_phaseII: 10000000
discount: 0.99
epsilon: 0.10
alternate_loss: False
visualize: False
start_steps: 2000
target_update_freq: 3000
update_every: 2000  #update maybe?
tau: 0.001
num_updates: 4

# TODO: set alpha value for target / base it off of standard DQN

